### PR TITLE
Solving npm install and npm start fail issue

### PR DESCRIPTION
**Pull request by ajhsu**
Hi Jeremy,

I got 2 error when i was building the sample
1. When I was doing `npm install`, it occurred an error that says:

```
npm ERR! fetch failed https://raw.githubusercontent.com/coodoo/foo/master/flux.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

And I've read the Notice from README and found that flux on npm was updated to [v2.0.3](https://www.npmjs.com/package/flux).

So I removed the `npm-shrinkwrap.json` and make `npm install` works as usual.
1. `npm start` will lost `build/bundle.js` when the `build` folder wasn't exist, which will makes Client-side js file missing.

So I preserved the `build` with `.keep` file but not to track files in `build` folder. And `npm start` works fine with a pre-exist, empty `build` folder in the end.

### CODE REVIEW

**Comment by coodoo** [comment]
@ajhsu  Hey AJ, thanks for sending over the bug report, I've moved `flux.tgz` into this repo hence has the access error issue fixed, could you please give it a try again? Thanks. 

As a side note, although the readme on `npm` states it's `v2.0.3`, but the content itself is still outdated version, you could verify this by installing from npm and compare the `Dispatcher.js` file.

**Comment by kytu800** [comment]
great!

**Comment by ajhsu** [comment]
Still have the issue.. is that only my problem?

```
npm ERR! fetch failed https://raw.githubusercontent.com/coodoo/react-alt-isomorphic-example/master/flux.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by tomchentw** [comment]
# Running on current `code:master` branch

``` log
➜  react-alt-isomorphic-example git:(master) npm start

> @ start /Users/tomchentw/repos/react-alt-isomorphic-example
> npm run build& npm run server


> @ build /Users/tomchentw/repos/react-alt-isomorphic-example
> webpack -d --progress --watch


> @ server /Users/tomchentw/repos/react-alt-isomorphic-example
> babel-node server.js

 10% 0/1 build modules
 40% 2/4 build modulesmodule.js:338
    throw err;
          ^
Error: Cannot find module 'iso'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tomchentw/repos/react-alt-isomorphic-example/server.js:8:11)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/tomchentw/repos/react-alt-isomorphic-example/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tomchentw/repos/react-alt-isomorphic-example/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ server: `babel-node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ server script 'babel-node server.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomchentw/repos/react-alt-isomorphic-example/npm-debug.log

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `npm run build& npm run server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'npm run build& npm run server'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build& npm run server
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomchentw/repos/react-alt-isomorphic-example/npm-debug.log
➜  react-alt-isomorph 59% 50/61 build modules
Hash: 15108a1028b29027fae8                   
Version: webpack 1.9.11
Time: 3717ms
        Asset     Size  Chunks             Chunk Names
    bundle.js   910 kB       0  [emitted]  boot
bundle.js.map  1.03 MB       0  [emitted]  boot
    + 199 hidden modules

ERROR in ./js/boot.js
Module not found: Error: Cannot resolve module 'iso' in /Users/tomchentw/repos/react-alt-isomorphic-example/js
 @ ./js/boot.js 9:10-24
```

**Comment by coodoo** [comment]
Just tried again and it worked, can you try `npm cache clean` and install again?

**Comment by tomchentw** [comment]
# Running on current `code:master` branch

``` log
➜  react-alt-isomorphic-example git:(master) ll node_modules 
total 0
drwxr-xr-x  25 tomchentw  staff   850B Jun 15 10:55 alt
drwxr-xr-x  10 tomchentw  staff   340B Jun 15 10:55 babel
drwxr-xr-x  24 tomchentw  staff   816B Jun 15 10:55 babel-core
drwxr-xr-x  15 tomchentw  staff   510B Jun 15 10:55 babel-loader
drwxr-xr-x   9 tomchentw  staff   306B Jun 15 10:55 babelify
drwxr-xr-x  11 tomchentw  staff   374B Jun 15 10:55 browserify-notify
drwxr-xr-x  22 tomchentw  staff   748B Jun 15 10:55 es5-shim
drwxr-xr-x   8 tomchentw  staff   272B Jun 15 10:55 es6-promise
drwxr-xr-x   9 tomchentw  staff   306B Jun 15 10:55 express
drwxr-xr-x   5 tomchentw  staff   170B Jun 15 10:55 json-loader
drwxr-xr-x   7 tomchentw  staff   238B Jun 15 10:55 node-libs-browser
drwxr-xr-x   6 tomchentw  staff   204B Jun 15 10:55 object-assign
drwxr-xr-x   8 tomchentw  staff   272B Jun 15 10:55 page
drwxr-xr-x   9 tomchentw  staff   306B Jun 15 10:55 react
drwxr-xr-x   9 tomchentw  staff   306B Jun 15 10:55 uglify-js
drwxr-xr-x  11 tomchentw  staff   374B Jun 15 10:55 webpack
➜  react-alt-isomorphic-example git:(master) 
```

**Comment by coodoo** [comment]
Just pushed a fix and confirmed working, closing for now, thanks for help out.

**Pull request closed without merging**
